2017/09/30 07:32:26 [error] 32#0: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: default_server, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost"
2017/09/30 07:32:32 [error] 32#0: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: default_server, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost"
